apiVersion: v1
kind: Template
metadata:
  name: dvo-selectorsyncset-template
parameters:
  - name: REGISTRY_IMG
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: true
  - name: REPO_NAME
    value: deployment-validation-operator
    required: true
  - name: DISPLAY_NAME
    value: Deployment Validation Operator
    required: true
  - name: CHANNEL
    value: "alpha"
    displayName: OLM subscription channel
    description: OLM subscription channel
    required: true
  - name: TARGET_ORG
    displayName: Target organization
    description: Target api.openshift.com organization to deploy to
    required: true
objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      annotations:
        component-display-name: ${DISPLAY_NAME}
        component-name: ${REPO_NAME}
      labels:
        managed.openshift.io/gitHash: ${IMAGE_TAG}
        managed.openshift.io/gitRepoName: ${REPO_NAME}
        managed.openshift.io/osd: "true"
      name: deployment-validation-operator
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/managed: "true"
        matchExpressions:
          - key: hive.openshift.io/version-major-minor
            operator: NotIn
            values: ["4.1", "4.2", "4.3", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9", "4.10"]
          - key: hive.openshift.io/version-major-minor-patch
            operator: NotIn
            values: ["4.11.0", "4.11.1", "4.11.2", "4.11.3", "4.11.4", "4.11.5", "4.11.6", "4.11.7", "4.11.8", "4.11.9"]
      resourceApplyMode: Sync
      resources:
        - apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-deployment-validation-operator
            labels:
              openshift.io/cluster-monitoring: "true"
        - apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: deployment-validation-operator-catalog
            namespace: openshift-deployment-validation-operator
          spec:
            sourceType: grpc
            image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
            displayName: Deployment Validation Operator
            publisher: Red Hat
        - apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: deployment-validation-operator-og
            namespace: openshift-deployment-validation-operator
            annotations:
              olm.operatorframework.io/exclude-global-namespace-resolution: "true"
          spec:
            upgradeStrategy: TechPreviewUnsafeFailForward
            targetNamespaces:
              - openshift-deployment-validation-operator
        - apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: deployment-validation-operator
            namespace: openshift-deployment-validation-operator
          spec:
            channel: ${CHANNEL}
            config:
              env:
              - name: "NAMESPACE_IGNORE_PATTERN"
                value: "^(openshift.*|kube-.*|default|dedicated-admin|redhat-.*|acm|addon-dba-operator|codeready-.*|prow)$"
            name: deployment-validation-operator
            source: deployment-validation-operator-catalog
            sourceNamespace: openshift-deployment-validation-operator
        - apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: allow-from-openshift-insights
            namespace: openshift-deployment-validation-operator
          spec:
            podSelector: {}
            ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      name: openshift-insights
          policyTypes:
            - Ingress
        - apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: allow-from-openshift-olm
            namespace: openshift-deployment-validation-operator
          spec:
            podSelector: {}
            ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      name: openshift-operator-lifecycle-manager
          policyTypes:
            - Ingress
        - apiVersion: v1
          kind: Service
          metadata:
            name: deployment-validation-operator-metrics
            namespace: openshift-deployment-validation-operator
            labels:
              name: deployment-validation-operator
          spec:
            ports:
            - name: http-metrics
              port: 8383
              protocol: TCP
              targetPort: 8383
            selector:
              name: deployment-validation-operator
        - apiVersion: v1
          kind: ConfigMap
          metadata:
            name: deployment-validation-operator-config
            namespace: openshift-deployment-validation-operator
            labels:
              name: deployment-validation-operator
          data:
            deployment-validation-operator-config.yaml: |-
              checks:
                # if doNotAutoAddDefaults is true, default checks are not automatically added.
                doNotAutoAddDefaults: false

                # addAllBuiltIn, if set, adds all built-in checks. This allows users to
                # explicitly opt-out of checks that are not relevant using Exclude.
                # Takes precedence over doNotAutoAddDefaults, if both are set.
                addAllBuiltIn: true
