version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/build"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "app-sre/boilerplate"
        # don't upgrade boilerplate via these means
      - dependency-name: "openshift4/ose-operator-registry"
        # don't upgrade ose-operator-registry via these means
