run:
  timeout: 5m

linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - gofmt
  - goimports
  - golint
  - misspell
  - unused
  - gocyclo
  - varcheck
  - maligned
  - interfacer
  - unconvert
  - goconst
  - gosec
  - lll

linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0

  lll:
    line-length: 120
    tab-width: 8

  gofmt:
    simplify: false
