run:
  timeout: 5m

linters:
  disable-all: true
  enable:
  - gofmt
  - goimports
  - revive
  - govet
  - misspell
  - unused
  - gocyclo
  - unconvert
  - goconst
  - gosec
  - lll
  - staticcheck

linters-settings:
  lll:
    line-length: 120
    tab-width: 8
