version: "2"
linters:
  default: none
  enable:
    - goconst
    - gocyclo
    - gosec
    - govet
    - lll
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    lll:
      line-length: 120
      tab-width: 8
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
