#!/usr/bin/env bash

REPO_ROOT=$(git rev-parse --show-toplevel)
source $REPO_ROOT/boilerplate/_lib/common.sh
source $REPO_ROOT/boilerplate/_lib/release.sh

usage() {
    cat <<EOF
$CMD

Analyzes the openshift/release footprint of onboarded boilerplate
subscribers. For each subscriber, prints the delta, if any, between the
existing and expected prow configuration.
EOF
    exit -1
}

source $REPO_ROOT/boilerplate/_lib/subscriber.sh

## prow_config ORG PROJ
#
# Downloads the ci-operator configuration file from openshift/release for the
# specified consuming project. Prints to stdout the path to the file. If the
# file does not exist on the server, there is no output.
#
# Set the TMPD global before invoking this.
prow_config() {
    local org=$1
    local proj=$2
    local p=https://raw.githubusercontent.com/$RELEASE_REPO/master/ci-operator/config/$org/$proj
    local f
    for branch in master main; do
        f=$org-$proj-$branch.yaml
        local c="$(curl -s $p/$f)"
        if [[ "$c" != "404: Not Found" ]]; then
            # Remove the zz_generated_metadata section
            echo "$c" | yq d - zz_generated_metadata > $TMPD/$f
            echo $TMPD/$f
            return
        fi
    done
}

## expected_prow_config PROJ
#
# Prints to stdout (most of) the expected prow configuration for the specified
# PROJ. The `zz_generated_metadata` section is omitted.
expected_prow_config() {
    local consumer_name=$1
    # TODO: DRY this with what's in prow-config.
    # Do it by making it a template in the convention dir.
    cat <<EOF
build_root:
  from_repository: true
images:
- dockerfile_path: build/Dockerfile
  to: unused
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: coverage
  commands: |
    export CODECOV_TOKEN=\$(cat /tmp/secret/CODECOV_TOKEN)
    make coverage
  container:
    from: src
  secret:
    mount_path: /tmp/secret
    name: ${consumer_name}-codecov-token
- as: publish-coverage
  commands: |
    export CODECOV_TOKEN=\$(cat /tmp/secret/CODECOV_TOKEN)
    make coverage
  container:
    from: src
  postsubmit: true
  secret:
    mount_path: /tmp/secret
    name: ${consumer_name}-codecov-token
- as: lint
  commands: make lint
  container:
    from: src
- as: test
  commands: make test
  container:
    from: src
- as: validate
  commands: make validate
  container:
    from: src
EOF
}

TMPD=$(mktemp -d)
trap "rm -fr $TMPD" EXIT

for subscriber in $(subscriber_list onboarded); do
    banner $subscriber
    org=${subscriber%/*}
    proj=${subscriber#*/}
    pc=$(prow_config $org $proj)
    if [[ -z "$pc" ]]; then
        echo "=== No configuration ==="
    else
        d="$(expected_prow_config $proj | diff -w - $pc)"
        if [[ -z "$d" ]]; then
            echo "=== A-OK ==="
        else
            echo "$d"
        fi
    fi
done
