#!/usr/bin/env bash

REPO_ROOT=$(git rev-parse --show-toplevel)
source $REPO_ROOT/boilerplate/_lib/common.sh

declare -A SUBCOMMANDS
SUBCOMMANDS=(
    # TODO:
    # [bootstrap]='Bootstrap a new subscriber'
    # [codecov-secret-mapping]='Propose codecov secret mapping to openshift/release'
    # [prow-config]='Propose standardized prow configuration to openshift/release'
    [update]='Update an already-onboarded subscriber'
)

source $REPO_ROOT/boilerplate/_lib/subscriber.sh
