---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: prod-release-v0-7-16-managed-clusters-rc1-2026-07-14
  namespace: dvo-obsint-tenant
spec:
 releasePlan: release-plan-managed-clusters-operator
 snapshot: prod-snapshot-v0-7-16-managed-clusters-rc1-2026-07-14
 data:
  releaseNotes:
    topic: Deployment Validation Operator 0.7.16
    synopsis: Maintenance update
    description: |
      This release resolves issues with outdated libraries and vulnerabilities present in the 0.7.15 release.
    solution: |
      Before applying this update, make sure all previously released errata relevant to your system have been applied. For details on how to apply this update, refer to: https://access.redhat.com/articles/11258
    references: []
