---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
 name: prod-release-fbc-4-16-20250703-01
 namespace: dvo-obsint-tenant
spec:
 releasePlan: release-plan-fbc-prod-4-16
 snapshot: fbc-ocp4-16-5xwd2
 data:
  releaseNotes:
    topic: Deployment Validation Operator FBC for Openshift v4.16
    synopsis: FBC update
    description: |
      This release includes catalog fragments until DVO 0.7.9
    solution: |
      Before applying this update, make sure all previously released errata relevant to your system have been applied. For details on how to apply this update, refer to: https://access.redhat.com/articles/11258
    references: []
