#!/bin/bash -e

source $CONVENTION_ROOT/_lib/common.sh

# No PRE
[[ "$1" == "PRE" ]] && exit 0

# Expect POST
[[ "$1" == "POST" ]] || err "Got a parameter I don't understand: '$1'. Did the infrastructure change?"

for f in .codecov.yml .ci-operator.yaml; do
    echo "Copying $f to your repository root."
    cp ${HERE}/$f $REPO_ROOT
done

cat <<EOF
=====================
THINGS YOU NEED TO DO
=====================
- Make sure the following line is in your base Makefile:

include boilerplate/generated-includes.mk

- Remove any other 'include' lines, unless they're for things truly
  unique to your repository. (Otherwise, consider proposing them to
  boilerplate.)

- Delete any obsolete files you're no longer including.

- Make sure you are properly integrated with codecov.io:
  https://github.com/openshift/ops-sop/blob/93d100347746ce04ad552591136818f82043c648/services/codecov.md#generate-the-codecovio-token

- Make sure your prow and app-sre pipeline configurations use the
  build_root configuration and standard targets described in the README.
EOF
