apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: deployment-validation-operator
  name: deployment-validation-operator-metrics
spec:
  ports:
  - name: http-metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    name: deployment-validation-operator
status:
  loadBalancer: {}
