# Applying this manifest will trigger a new release.
# Temporary or automatic konflux snapshots may deliver a failed release
# To check the process and logs, connect to the UI and navigate to Application > Releases > [release-name] > PipelineRun
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
 name: staging-release-snapshot-0425-01
 namespace: dvo-obsint-tenant
spec:
 releasePlan: release-plan-staging
 snapshot: staging-snapshot-0425-01
 data:
  releaseNotes:
   topic: Test Release
   synopsis: Test to debug Release process
   description: Test to debug Release process
   solution: ""
   references: ""
