# Applying this manifest will trigger a new release.
# Temporary or automatic konflux snapshots may deliver a failed release
# To check the process and logs, connect to the UI and navigate to Application > Releases > [release-name] > PipelineRun
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
 name: staging-release-v0-7-15-rc1-2026-04-23
 namespace: dvo-obsint-tenant
spec:
 releasePlan: release-plan-staging
 snapshot: deployment-validation-operator-20260423-070603-000
 data:
  releaseNotes:
   topic: Staging Release
   synopsis: Staging Release previous to creating the Prod Release
   description: Test the Release process
   solution: ""
   references: []
