# This manifest adds a new RoleBinding for the user to access the Konflux UI.
# * role param specifies the level of permissions among: admin, maintainer, contributor
# * username param specifies the RH user who will be granted the permissions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    konflux-ci.dev/type: user
  name: konflux-${role}-${username}-actions-user
  namespace: dvo-obsint-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konflux-${role}-user-actions
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ${username}
