---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: prod-mirror-set
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/redhat-user-workloads/dvo-obsint-tenant/deployment-validation-operator/deployment-validation-operator@sha256:cd780af5bafe6eebf282b23f01dd0fc2320d249769a1567539a5e678c3a752bc
      source: registry.redhat.io/dvo/deployment-validation-rhel8-operator@sha256:cd780af5bafe6eebf282b23f01dd0fc2320d249769a1567539a5e678c3a752bc
