---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: prod-mirror-set
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/redhat-user-workloads/dvo-obsint-tenant/deployment-validation-operator/deployment-validation-operator@sha256:0dfa50191d0d7dca407de7b451426abf4a504ea8481a0c34dd82dd54665ad5f3
      source: registry.redhat.io/dvo/deployment-validation-rhel8-operator@sha256:0dfa50191d0d7dca407de7b451426abf4a504ea8481a0c34dd82dd54665ad5f3
