# THIS FILE IS GENERATED BY BOILERPLATE. DO NOT EDIT.
# This file automatically includes any *.mk files in your subscribed
# conventions. Please ensure your base Makefile includes only this file.
include boilerplate/openshift/golang-osd-operator/project.mk
include boilerplate/openshift/golang-osd-operator/standard.mk
