apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-validation-operator
subjects:
- kind: ServiceAccount
  name: deployment-validation-operator
  namespace: deployment-validation-operator
roleRef:
  kind: ClusterRole
  name: deployment-validation-operator
  apiGroup: rbac.authorization.k8s.io
