---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-validation-operator-config
  labels:
    name: deployment-validation-operator
data:
  deployment-validation-operator-config.yaml: |-
    checks:
      # if doNotAutoAddDefaults is true, default checks are not automatically added.
      doNotAutoAddDefaults: false

      # addAllBuiltIn, if set, adds all built-in checks. This allows users to
      # explicitly opt-out of checks that are not relevant using Exclude.
      # Takes precedence over doNotAutoAddDefaults, if both are set.
      addAllBuiltIn: true
