---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-validation-operator-config
  labels:
    name: deployment-validation-operator
data:
  deployment-validation-operator-config.yaml: |-
    checks:
      doNotAutoAddDefaults: true
      addAllBuiltIn: false
      include:
      - "host-ipc"
      - "host-network"
      - "host-pid"
      - "non-isolated-pod"
      - "pdb-max-unavailable"
      - "pdb-min-available"
      - "privilege-escalation-container"
      - "privileged-container"
      - "run-as-non-root"
      - "unsafe-sysctls"
      - "unset-cpu-requirements"
      - "unset-memory-requirements"
