---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-validation-operator-config
  labels:
    name: deployment-validation-operator
data:
  deployment-validation-operator-config.yaml: |-
    checks:
      doNotAutoAddDefaults: true
      addAllBuiltIn: false
      include: ["pdb-max-unavailable", "pdb-min-available", "non-isolated-pod", "unset-cpu-requirements", "unset-memory-requirements"]