---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-validation-operator
  namespace: deployment-validation-operator
subjects:
- kind: ServiceAccount
  name: deployment-validation-operator
  namespace: deployment-validation-operator # if using a custom namespace to deploy DVO components, change this line !!!
roleRef:
  kind: Role
  name: deployment-validation-operator
  apiGroup: rbac.authorization.k8s.io
