---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-validation-operator
  namespace: deployment-validation-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - services/finalizers
  verbs:
  - get
  - create
  - list
  - delete
  - update
  - watch
  - patch
- apiGroups:
  - apps
  resourceNames:
  - deployment-validation-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
