---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-validation-operator
  namespace: deployment-validation-operator
subjects:
- kind: ServiceAccount
  name: deployment-validation-operator
  namespace: deployment-validation-operator
roleRef:
  kind: Role
  name: deployment-validation-operator
  apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: deployment-validation-operator
#   namespace: extra-dvo-testing
# subjects:
# - kind: ServiceAccount
#   name: deployment-validation-operator
#   namespace: <custom-namespace-here>
# roleRef:
#   kind: Role
#   name: deployment-validation-operator
#   apiGroup: rbac.authorization.k8s.io
