---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-validation-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - get
  - create
  - list
  - delete
  - update
  - watch
  - patch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
