apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: deployment-validation-operator
spec:
  replicas: 2
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      prometheus: deployment-validation-operator
