---
apiVersion: v1
kind: Template
metadata:
  name: deployment-validation-operator-service-monitor-${NAMESPACE}
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      prometheus: dvo-${NAMESPACE}
    name: dvo-${NAMESPACE}
  spec:
    endpoints:
    - interval: 5s
      port: http-metrics
      scheme: http
    namespaceSelector:
      matchNames:
      - ${NAMESPACE}
    selector:
      matchLabels:
        name: ${NAMESPACE}
parameters:
- name: NAMESPACE
  value: ""
  displayName: namespace with installed prometheus-metrics deployment-validation-operator service-monitor
  description: namespace to install prometheus-metrics deployment-validation-operator service-monitor to
  required: true
