---
apiVersion: v1
kind: Template
metadata:
  name: deployment-validation-operator-service-monitor-${NAMESPACE}
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      prometheus: deployment-validation-operator
    name: deployment-validation-operator
  spec:
    endpoints:
    - interval: 5s
      port: http-metrics
      scheme: http
    namespaceSelector:
      matchNames:
      - ${NAMESPACE}
    selector:
      matchLabels:
        name: deployment-validation-operator
parameters:
- name: NAMESPACE
  value: ""
  displayName: namespace for deployment-validation-operator service-monitor to select
  description: namespace is deployment-validation-operator service-monitor is selected to
  required: true
