customChecks:
  - name: test-minimum-replicas
    description: "some description"
    remediation: "some remediation"
    template: minimum-replicas
    params:
      minReplicas: 3
    scope:
      objectKinds:
        - DeploymentLike     
checks:
      doNotAutoAddDefaults: false
      addAllBuiltIn: true
      include:
      - "host-ipc"
      - "host-network"
      - "host-pid"
      - "non-isolated-pod"
      - "pdb-max-unavailable"
      - "pdb-min-available"
      - "privilege-escalation-container"
      - "privileged-container"
      - "run-as-non-root"
      - "unsafe-sysctls"
      - "unset-cpu-requirements"
      - "unset-memory-requirements"